-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations
/*
CREATE TABLE "permissions" (
	"id" serial PRIMARY KEY NOT NULL,
	"action" text NOT NULL,
	"resource" text NOT NULL,
	CONSTRAINT "permissions_action_check" CHECK (action = ANY (ARRAY['manage'::text, 'create'::text, 'update'::text, 'read'::text, 'delete'::text]))
);
--> statement-breakpoint
ALTER TABLE "permissions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "users" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now(),
	"full_name" text NOT NULL,
	"email_id" text,
	"phone_no" text,
	"activated_at" timestamp with time zone,
	"modified_at" timestamp with time zone DEFAULT now(),
	"last_login" timestamp with time zone,
	"base_role" smallint NOT NULL,
	"user_name" text,
	"password_hash" text,
	CONSTRAINT "users_email_id_key" UNIQUE("email_id"),
	CONSTRAINT "users_user_name_key" UNIQUE("user_name"),
	CONSTRAINT "users_user_name_check" CHECK (length(user_name) <= 32)
);
--> statement-breakpoint
ALTER TABLE "users" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "courses" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" text NOT NULL,
	"abbrv" text NOT NULL,
	"hod_id" uuid,
	"department_id" uuid DEFAULT 'aa0239e4-93d5-4231-a167-245487e2a2c2' NOT NULL
);
--> statement-breakpoint
ALTER TABLE "courses" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "roles" (
	"id" smallint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "roles_role_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 32767 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"scope" text NOT NULL,
	CONSTRAINT "roles_role_scope_check" CHECK (scope = ANY (ARRAY['base'::text, 'extension'::text, 'both'::text]))
);
--> statement-breakpoint
ALTER TABLE "roles" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "teachers" (
	"user_id" uuid PRIMARY KEY NOT NULL,
	"abbrv" text NOT NULL
);
--> statement-breakpoint
ALTER TABLE "teachers" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "assignment_upload_logs" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"assignment_id" uuid NOT NULL,
	"student_id" uuid NOT NULL,
	"attachment_key" text NOT NULL,
	"uploaded_at" timestamp with time zone DEFAULT now() NOT NULL,
	"upload_completed_at" timestamp with time zone,
	"status" text DEFAULT 'processing' NOT NULL,
	"file_size" bigint,
	"etag" text,
	CONSTRAINT "assignment_upload_logs_status_check" CHECK (status = ANY (ARRAY['success'::text, 'processing'::text, 'failed'::text]))
);
--> statement-breakpoint
ALTER TABLE "assignment_upload_logs" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "students" (
	"user_id" uuid PRIMARY KEY NOT NULL,
	"roll_no" text NOT NULL,
	"reg_no" text NOT NULL,
	"dob" date,
	"semester_id" smallint NOT NULL,
	"course_id" uuid NOT NULL,
	CONSTRAINT "students_roll_no_key" UNIQUE("roll_no"),
	CONSTRAINT "students_reg_no_key" UNIQUE("reg_no")
);
--> statement-breakpoint
ALTER TABLE "students" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "assignments" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"title" text NOT NULL,
	"description" text,
	"assigned_by" uuid,
	"semester_id" smallint NOT NULL,
	"course_id" uuid NOT NULL,
	"subject_code" text NOT NULL,
	"subject_name" text NOT NULL,
	"max_marks" smallint,
	"attachment_url" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"due_at" timestamp with time zone NOT NULL,
	"expires_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
ALTER TABLE "assignments" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "departments" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" text NOT NULL,
	"abbrv" text NOT NULL,
	CONSTRAINT "departments_name_key" UNIQUE("name"),
	CONSTRAINT "departments_abbrv_key" UNIQUE("abbrv")
);
--> statement-breakpoint
ALTER TABLE "departments" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "otp_sessions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"email_id" text NOT NULL,
	"purpose" text NOT NULL,
	"otp_hash" text NOT NULL,
	"status" text DEFAULT 'pending',
	"otp_attempts" smallint DEFAULT 0,
	"max_otp_attempts" smallint DEFAULT 5,
	"resend_count" smallint DEFAULT 0,
	"max_resend" smallint DEFAULT 3,
	"change_email_count" smallint DEFAULT 0,
	"max_email_change" smallint DEFAULT 3,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now(),
	"expires_at" timestamp with time zone DEFAULT (now() + '00:03:00'::interval),
	"ip" "inet",
	"user_agent" text,
	CONSTRAINT "otp_sessions_purpose_check" CHECK (purpose = ANY (ARRAY['email_verification'::text, 'password_reset'::text, 'email_change'::text])),
	CONSTRAINT "otp_sessions_status_check" CHECK (status = ANY (ARRAY['pending'::text, 'used'::text, 'expired'::text]))
);
--> statement-breakpoint
ALTER TABLE "otp_sessions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "role_permissions" (
	"role_id" smallint NOT NULL,
	"permission_id" integer NOT NULL,
	CONSTRAINT "role_permissions_pkey" PRIMARY KEY("role_id","permission_id")
);
--> statement-breakpoint
ALTER TABLE "role_permissions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "semesters" (
	"id" smallint NOT NULL,
	"course_id" uuid NOT NULL,
	CONSTRAINT "semesters_pkey" PRIMARY KEY("id","course_id")
);
--> statement-breakpoint
ALTER TABLE "semesters" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "role_extended_users" (
	"user_id" uuid NOT NULL,
	"role_id" smallint NOT NULL,
	CONSTRAINT "role_extended_users_pkey" PRIMARY KEY("user_id","role_id")
);
--> statement-breakpoint
ALTER TABLE "role_extended_users" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "teacher_departments" (
	"teacher_id" uuid NOT NULL,
	"department_id" uuid NOT NULL,
	CONSTRAINT "teacher_departments_pkey" PRIMARY KEY("teacher_id","department_id")
);
--> statement-breakpoint
ALTER TABLE "teacher_departments" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "teacher_subjects" (
	"subject_code" text NOT NULL,
	"subject_name" text NOT NULL,
	"teacher_id" uuid NOT NULL,
	CONSTRAINT "teacher_subjects_pkey" PRIMARY KEY("subject_code","subject_name","teacher_id")
);
--> statement-breakpoint
ALTER TABLE "teacher_subjects" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "subjects" (
	"code" text NOT NULL,
	"name" text NOT NULL,
	"course_id" uuid NOT NULL,
	"semester_id" smallint NOT NULL,
	CONSTRAINT "subjects_pkey" PRIMARY KEY("code","name")
);
--> statement-breakpoint
ALTER TABLE "subjects" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "student_assignments" (
	"assignment_id" uuid NOT NULL,
	"student_id" uuid NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"submitted_at" timestamp with time zone,
	"is_late" boolean DEFAULT false NOT NULL,
	"attachment_key" text,
	CONSTRAINT "student_assignments_pkey" PRIMARY KEY("assignment_id","student_id"),
	CONSTRAINT "student_assignments_status_check" CHECK (status = ANY (ARRAY['pending'::text, 'submitted'::text]))
);
--> statement-breakpoint
ALTER TABLE "student_assignments" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "users" ADD CONSTRAINT "users_base_role_fkey" FOREIGN KEY ("base_role") REFERENCES "public"."roles"("id") ON DELETE restrict ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "courses" ADD CONSTRAINT "courses_department_id_fkey" FOREIGN KEY ("department_id") REFERENCES "public"."departments"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "courses" ADD CONSTRAINT "departments_hod_id_fkey" FOREIGN KEY ("hod_id") REFERENCES "public"."teachers"("user_id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "teachers" ADD CONSTRAINT "teachers_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "assignment_upload_logs" ADD CONSTRAINT "assignment_upload_logs_assignment_id_fkey" FOREIGN KEY ("assignment_id") REFERENCES "public"."assignments"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "assignment_upload_logs" ADD CONSTRAINT "assignment_upload_logs_student_id_fkey" FOREIGN KEY ("student_id") REFERENCES "public"."students"("user_id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "students" ADD CONSTRAINT "fk_semester" FOREIGN KEY ("semester_id","course_id") REFERENCES "public"."semesters"("id","course_id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "students" ADD CONSTRAINT "students_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "assignments" ADD CONSTRAINT "assignments_assigned_by_fkey" FOREIGN KEY ("assigned_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "assignments" ADD CONSTRAINT "assignments_semester_id_course_id_fkey" FOREIGN KEY ("semester_id","course_id") REFERENCES "public"."semesters"("id","course_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "assignments" ADD CONSTRAINT "assignments_subject_code_subject_name_fkey" FOREIGN KEY ("subject_code","subject_name") REFERENCES "public"."subjects"("code","name") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "otp_sessions" ADD CONSTRAINT "otp_sessions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "role_permissions" ADD CONSTRAINT "role_permissions_permission_id_fkey" FOREIGN KEY ("permission_id") REFERENCES "public"."permissions"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "role_permissions" ADD CONSTRAINT "role_permissions_role_id_fkey" FOREIGN KEY ("role_id") REFERENCES "public"."roles"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "semesters" ADD CONSTRAINT "semesters_course_id_fkey" FOREIGN KEY ("course_id") REFERENCES "public"."courses"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "role_extended_users" ADD CONSTRAINT "role_extended_users_role_id_fkey" FOREIGN KEY ("role_id") REFERENCES "public"."roles"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "role_extended_users" ADD CONSTRAINT "role_extended_users_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "teacher_departments" ADD CONSTRAINT "teacher_departments_department_id_fkey" FOREIGN KEY ("department_id") REFERENCES "public"."departments"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "teacher_departments" ADD CONSTRAINT "teacher_departments_teacher_id_fkey" FOREIGN KEY ("teacher_id") REFERENCES "public"."teachers"("user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "teacher_subjects" ADD CONSTRAINT "teacher_subjects_subject_code_subject_name_fkey" FOREIGN KEY ("subject_code","subject_name") REFERENCES "public"."subjects"("code","name") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "teacher_subjects" ADD CONSTRAINT "teacher_subjects_teacher_id_fkey" FOREIGN KEY ("teacher_id") REFERENCES "public"."teachers"("user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "subjects" ADD CONSTRAINT "subjects_semester_id_course_id_fkey" FOREIGN KEY ("course_id","semester_id") REFERENCES "public"."semesters"("id","course_id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "student_assignments" ADD CONSTRAINT "student_assignments_assignment_id_fkey" FOREIGN KEY ("assignment_id") REFERENCES "public"."assignments"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "student_assignments" ADD CONSTRAINT "student_assignments_student_id_fkey" FOREIGN KEY ("student_id") REFERENCES "public"."students"("user_id") ON DELETE cascade ON UPDATE cascade;
*/